import Head from 'next/head'
import Image from 'next/image'
import { Open_Sans } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { useEffect } from 'react';

const openSans = Open_Sans({ subsets: ['latin'] });

export default function Home() {
  useEffect(() => {
    window.location.href="/login"
  }, [])
  return (
    <>
      <Head>
        <title>Touring Guide</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

      </main>
    </>
  )
}
